### ISSUE TITLE
Can't fine tune Phi-2

### ISSUE THREAD

**Issue by yukiarimo** [brevdev/notebooks#10]
GPU RAM goes to the max when startig

**Comment by jingzhaoou** [comment]
I ran the Phi-2 finetune code on a L4 instance with 24GB VRAM. The script worked well. Use `nvidia-smi` to ensure no other process is using the GPU. Others, with a 4-bit 7B quantized model, 24GB VRAM is very sufficient in my test cases. It used way less than 50% of the 24GB VRAM. I hope this helps.
