### ISSUE TITLE
What is the transfomers, accelerate and deepspeed version you are using

### ISSUE THREAD

**Issue by robinsonmhj** [brevdev/notebooks#15]
Hi @harper-carroll 

Can you share the version of the following python package when you are quantizing the model?
 transfomers
accelerate
deepspeed 

To be specific, I am referring this code block

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

base_model_id = "mistralai/Mistral-7B-v0.1"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model = AutoModelForCausalLM.from_pretrained(base_model_id, quantization_config=bnb_config, device_map="auto")
```

**Comment by ishandhanani** [comment]
Hi @robinsonmhj - we have not pinned any version when creating this notebook. We are using the most up to date versions. Curious as to why you're using deepspeed with that notebook?
