### ISSUE TITLE
pip install problem 

### ISSUE THREAD

**Issue by SHIMURA0** [brevdev/notebooks#17]
Hello,

When I run the notebook that fine-tuning Phi2 on your own data, I met the error as follows when I pip install the required packages 
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/ubuntu/.pyenv/versions/3.10.14/etc/jupyter/nbconfig'
Consider using the `--user` option or check the permissions.

I will be grateful if you can teach how to fix this problem!

**Comment by ishandhanani** [comment]
Hi @SHIMURA0 - we made a fix to this! Let me know if you still hit it. Closing this issue

**Comment by SHIMURA0** [comment]
> Hi @SHIMURA0 - we made a fix to this! Let me know if you still hit it. Closing this issue

Thanks! In fact, this problem is resolved itself when I change the Python version and CUDA version I used on brew.dev, so I think maybe this is just some version compatibility issue. I am grateful by the way you actually fix this problem!
