### ISSUE TITLE
Bug when finetuning Mistral 7B

### ISSUE THREAD

**Issue by MLlove0402** [brevdev/notebooks#6]
Hello, Thanks you for great work
I'm follow your code mistral-finetune-own-data.ipynb, but when the code run at:
accelerator = Accelerator(fsdp_plugin=fsdp_plugin)
model = accelerator.prepare_model(model)

It throw an error:
ValueError: Must flatten tensors with uniform `requires_grad` when `use_orig_params=False`

How can i fix it.
Thanks you

**Comment by me-v2** [comment]
ValueError: Can't find 'adapter_config.json' when gguf-export.ipynb
